SELECT HACKER_ID,
       NAME,
       SUM(A)
FROM
  (SELECT S.HACKER_ID,
          H.NAME,
          MAX(S.SCORE) A
   FROM SUBMISSIONS S
   INNER JOIN HACKERS H ON H.HACKER_ID=S.HACKER_ID
   WHERE S.SCORE!=0
   GROUP BY S.HACKER_ID,
            H.NAME,
            S.CHALLENGE_ID)
GROUP BY HACKER_ID,
         NAME
ORDER BY 3 DESC,
         1;